---
layout: post
title:  "Go  Part 8"
author: haran
categories: [Golang,todd]
image: post_img/2022/03/03/go_main.png
beforetoc: "Go is a statically typed, compiled programming language designed at Google by Robert Griesemer, Rob Pike, and Ken Thompson. "
toc: true
comments: false
rating: 3.5
---

Understanding , checking errors , Printing and logging , Recover function , Errors with info

## 1-Understanding

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/1.jpg)

- better way to handle errors
- If I throw an error , put it right in the same plcae rather than using idioms such as `try and catch`

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/2.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/3.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/4.jpg)


- any method attach this `method ERROR()` also `type error`.

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/5.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/6.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/7.jpg)

- `New` function takes string as an input and throw error as an returm
- return `&errorString{text}` means errorstring address and value, this is look like composite literal `{}`
- `errorString` is unexported because it is in `lowerCase`. errorString is a structure which want  string`s`
- receiver of `Error()` method is `*errorString`.

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/8.jpg)

- you are o=implementing the `error` interface.

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/9.jpg)

## 2-Checking errors

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/10.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/11.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/12.jpg)

- above code there is an error
- `nil`  is reference type doesnot point to anything,it doesn't exist, there's no error.

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/13.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/14.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/15.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/16.jpg)


---
---

## Another Example

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/17.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/18.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/19.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/20.jpg)


- `io.copy(f,r)` => Read from that and write to that.


---
---

## Another Example

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/21.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/22.jpg)

- readAll => take byte size and return an error.

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/23.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/24.jpg)

## 3.Printing and Logging

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/25.jpg)


- `fmt.Println` => goes to standard output
- `log.Prinln` => goes to standard output , but you can write in to a file
- `log.Fatalln()` => we are shutting down game is  over , dead, throws non zero exit code , we're shutting down.
- `log.Panicln()` => we are not dead yet,It's panic,I am going to log it and in the worst case sceanrio programmes going to shut down. => In panic you can use `recover`

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/26.jpg)


### fmt.Println()

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/27.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/28.jpg)

### log.Println()

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/29.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/30.jpg)

- you can get your time stamp there

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/31.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/32.jpg)


![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/33.jpg)


### log.Fatalln

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/34.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/35.jpg)

- deferred functions are not run.

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/36.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/37.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/38.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/39.jpg)

### Log.Panicln()

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/40.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/41.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/42.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/43.jpg)


### panic()

### without logging panic

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/44.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/45.jpg)

- In the case panic , it will run the `defer()` function and work through the call stack and then you can also use recover to catch errors which you may know will happen.

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/46.jpg)


## 4-Recover function

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/47.jpg)


![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/48.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/49.jpg)

https://go.dev/blog/defer-panic-and-recover

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/50.jpg)

- if call to `OS` create fails , that function will create that clausing resource file.
- This can be remedied by putting a call to a source close before the second return statement
- This works, but there is a bug. If the call to os.Create fails, the function will return without closing the source file.
- This can be easily remedied by putting a call to `src.Close` before the second return statement.
-  but if the function were more complex the problem might not be so easily noticed and resolved.
- By introducing defer statements we can ensure that the files are always closed:

```go
func CopyFile(dstName, srcName string) (written int64, err error) {
    src, err := os.Open(srcName)
    if err != nil {
        return
    }
    defer src.Close()

    dst, err := os.Create(dstName)
    if err != nil {
        return
    }
    defer dst.Close()

    return io.Copy(dst, src)
}
```

- Defer statements allow us to think about closing each file right after opening it, guaranteeing that, regardless of the number of `return statements in the function,` the files _will_ be closed.

- The behavior of defer statements is straightforward and predictable. There are three simple rules:

1.  _A deferred function’s arguments are evaluated when the defer statement is evaluated._

- In this example, the expression “i” is evaluated when the Println call is deferred. 

- The deferred call will print “0” after the function returns.

```go
func a() {
    i := 0
    defer fmt.Println(i) // 0
    i++
    return
}
```

2.  _Deferred function calls are executed in Last In First Out order after the surrounding function returns._

This function prints “3210”:

```go
func b() {
    for i := 0; i < 4; i++ {
        defer fmt.Print(i)
    }
}
```

3.  _Deferred functions may read and assign to the returning function’s named return values._

- In this example, a deferred function increments the return value i _after_ the surrounding function returns. Thus, this function returns 2:

```go
func c() (i int) {
    defer func() { i++ }()
    return 1
}
```


This is convenient for modifying the error return value of a function; we will see an example of this shortly. 

`defer function called after returning`

in the above code stangely enough since it's the return it'll take 1 and add 1 to it which give us two kind of a

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/51.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/52.jpg)


**Panic** 

- is a built-in function that stops the ordinary flow of control and begins _panicking_. 

- When the function F calls panic, execution of F stops, any deferred functions in F are executed normally, and then F returns to its caller. 

- To the caller, F then behaves like a call to panic. The process continues up the stack until all functions in the current goroutine have returned, at which point the program crashes. 

- Panics can be initiated by invoking panic directly. They can also be caused by runtime errors, such as out-of-bounds array accesses

**Recover** 

- is a built-in function that regains control of a panicking goroutine. Recover is only useful inside deferred functions. 

- During normal execution, a call to recover will return nil and have no other effect. 

- If the current goroutine is panicking, a call to recover will capture the value given to panic and resume normal execution.

- Here’s an example program that demonstrates the mechanics of panic and defer:

```go
package main

import "fmt"

func main() {
    f()
    fmt.Println("Returned normally from f.")
}

func f() {
    defer func() {
        if r := recover(); r != nil {
            fmt.Println("Recovered in f", r)
        }
    }()
    fmt.Println("Calling g.")
    g(0)
    fmt.Println("Returned normally from g.")
}

func g(i int) {
    if i > 3 {
        fmt.Println("Panicking!")
        panic(fmt.Sprintf("%v", i))
    }
    defer fmt.Println("Defer in g", i)
    fmt.Println("Printing in g", i)
    g(i + 1)
}
```

- The function g takes the int i, and panics if i is greater than 3, or else it calls itself with the argument i+1. 

- The function f defers a function that calls recover and prints the recovered value (if it is non-nil). 

- Try to picture what the output of this program might be before reading on.

- The program will output:

```go
Calling g.
Printing in g 0
Printing in g 1
Printing in g 2
Printing in g 3
Panicking!
Defer in g 3
Defer in g 2
Defer in g 1
Defer in g 0
Recovered in f 4
Returned normally from f.
```

- If we remove the deferred function from f the panic is not recovered and reaches the top of the goroutine’s call stack, terminating the program. 

- This modified program will output:

```go
Calling g.
Printing in g 0
Printing in g 1
Printing in g 2
Printing in g 3
Panicking!
Defer in g 3
Defer in g 2
Defer in g 1
Defer in g 0
panic: 4
```

panic PC=0x2a9cd8
[stack trace omitted]

- For a real-world example of **panic** and **recover**, see the [json package](https://go.dev/pkg/encoding/json/) from the Go standard library. It encodes an interface with a set of recursive functions.

- If an error occurs when traversing the value, panic is called to unwind the stack to the top-level function call, which recovers from the panic and returns an appropriate error value (see the ‘error’ and ‘marshal’ methods of the encodeState type in [encode.go](https://go.dev/src/pkg/encoding/json/encode.go)).

- The convention in the Go libraries is that even when a package uses panic internally, its external API still presents explicit error return values.

- Other uses of **defer** (beyond the file.Close example given earlier) include releasing a mutex:

```go
mu.Lock()
defer mu.Unlock()
```

printing a footer:

```go
printHeader()
defer printFooter()
```

and more.

- In summary, the defer statement (with or without panic and recover) provides an unusual and powerful mechanism for control flow. 

- It can be used to model a number of features implemented by special-purpose structures in other programming languages. Try it out
![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/53.jpg)

**Summary**

- `F` is called we defer this function.\

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/54.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/55.jpg)

- so we defer that , that's deferred, we print line calling G
![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/56.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/57.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/58.jpg)


![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/59.jpg)

## 5-Errors with info

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/60.jpg)

- that's the type built in error , type form the built in package

### Errors New

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/61.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/62.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/63.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/64.jpg)

- Exported and Non Exported Capital and small

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/65.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/66.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/67.jpg)

---
---
![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/68.jpg)
![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/69.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/70.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/71.jpg)



![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/72.jpg)

---
---
### Example 4

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/73.jpg)


![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/74.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/75.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/76.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/77.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/78.jpg)

- fmt error format printing `fmt.Errorf`
---
---

### fmt.Errorf assigning at to a variable
![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/79.jpg)


![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/80.jpg)

- if you have a method attach to a type which has this signature `Error()`, then any valueof that type was be of type error interface , it will implicitly implements `error` interface.

- when we have a type like struct and it has a method with this signature `Error()` then it is also going any value of that type , it also implicitly implement the `error` interface

```go

type hello struct{ // that struct
	s String
}

func (h hello) Error() string {} // attched to the method Error()

type error interface { // Error() is part of the error interface
	Error() string
}

// then hello is also implement the error interface

func ls(e error) string {}

ls(hello)//ls also accept hello becasue it is also part of error interface

```

---
---
### Example  custom type error

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/81.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/82.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/83.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/84.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/85.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/86.jpg)

![dockerengine]({{ site.baseurl }}/post_img/2022/03/13_3/87.jpg)

